### ISSUE TITLE
Garantir que a base de dados Isis do DeCS esteja atualizada no serverofi5

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/DeCSHighlighter#1]
Colocar em um processo automático ou manual a atualização da base de dados DeCS em Isis no servidor serverofi5 sempre que a mesma for atualizada em outros servidores. Favor indicar a localização da mesma no serverofi5.

**Comment by falbrito** [comment]
A cada ano, após o processamento DeCS ser aprovado para publicação serão copiados os arquivos **decs.id**, **decs.mst** e **decs.xrf** para os servidores SERVEROFI4 e SERVEROFI5.

Os mesmos estão localizados em:
**serverofi[4|5]:/usr/local/bireme/tabs**

Para referência, a documentação de atualização está em:
http://wiki.bireme.org/intranet/index.php/Decs_utilizado_em_processos_ofi

Realizado.
