### ISSUE TITLE
Marcação do artigo "las" no idioma espanhol

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/DeCSHighlighter#18]
Quando o resumo está em espanhol, o artigo feminino plural "las" está sendo marcado, entretanto o mesmo não é termo DeCS/MeSH

**Comment by heitorbarbieri** [comment]
Por favor, verificar se nâo é somente um problema de configuração.

![AllLanguages](https://user-images.githubusercontent.com/2152778/79750669-b7260580-82e7-11ea-8036-93e3c64a5503.jpg)
![Spanish](https://user-images.githubusercontent.com/2152778/79750710-c60cb800-82e7-11ea-934d-caa5d4feb7ac.jpg)

**Comment by renatomurasaki** [comment]
Percebi isso dentro da interface do iAHx. Acho que você teria que rever o procedimento de marcação para considerar os diferentes idiomas que um resumo pode ter. Documentos LILACS podem apresentar 3 resumos no mesmo documento, em pt, es e en.

**Comment by renatomurasaki** [comment]
@heitorbarbieri acho que é isso mesmo, Heitor. Agora encontrei a situação "son", verbo ser na 3a pessoa do plural nos resumos em espanhol. O processamento não deve estar considerando esse contexto de idioma, pois é uma variável nova no procedimento, correto?

**Comment by heitorbarbieri** [comment]
Atualmente o processamento não leva em conta o idioma do texto. Poderemos aprimorar o processo  para levar em conta o idioma.

**Comment by heitorbarbieri** [comment]
No projeto MarkAbstract, o algoritmo agora procura todas as tags "ab" e "ab_&lt;lang>" e marca os descritores DeCS no primeiro caso conforme a especificação da lingua feita na tag &lt;la> e nos outros casos conforme a lingua especificada no próprio nome da tag, por exemplo
 &lt;ab_pt> marca os descritores em português.

commit 02a38fc
