### ISSUE TITLE
Implementar modificações na interface de forma a permitir uma melhor granularidade na escolha dos tipos de termos (conforme requerido no DeCSMeSHHighlighter

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/DeCSHighlighter#24]
Obs: as modificações não impactam a implementação atual do FI-Admin

**Comment by renatomurasaki** [comment]
@heitorbarbieri favor registrar aqui quais são as modificações

**Comment by heitorbarbieri** [comment]
Feito no commit 97d6851

**Comment by heitorbarbieri** [comment]
Conforme a página explicativa do MeSH (https://www.nlm.nih.gov/mesh/intro_record_types.html), existem 4 tipos de descritores (Main Headings, Publication Characteristics (Publication Types), Check Tags e Geographics), os 'qualifiers', os 'entry terms' (synonyms) e os 'supplementary records'.
À exceção do último, a interface do DecsHighlighter permite que se filtre ou não cada um deste termos com a utilização dos respectivos parâmetros:

- scanMainHeadings
- scanPublicationTypes
- scanCheckTags
- scanQualifiers
- scanGeographics
- scanEntryTerms

 Foi mantido, para compatibilidade com a chamada do Fi-Admin, e ampliado o parâmetro pubType onde:

pubType 'h' equivale a scanMainHeadings + scanEntryTerms 
pubType 'q' equivale a scanQualifiers + scanEntryTerms
pubType 't' equivale a scanPublicationTypes + scanEntryTerms
pubType 'c' equivale a scanCheckTags + scanEntryTerms
pubType 'g' equivale a scanGeographics + scanEntryTerms

**Comment by heitorbarbieri** [comment]
Na versão anterior só existiam os parâmetros:

- scanSynonyms (scanMainHeadings era constante e sempre igual a true)
- onlyPreCod

e o parâmetro pubType só aceitava os parâmetros 'h', 'q' e 't'
