### ISSUE TITLE
Atributo ID não está retornando o valor correto

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/DeCSHighlighter#26]
Por algum motivo, a API não está mais retornando o valor correto no atributo ID. Atualmente, a API está retornando o **ID do descritor,** mas é necessário retornar o **Identificador DeCS** para montar o link correto na sensibilização dos termos.

Segue exemplo do termo "Dengue" em uma pesquisa feita no Portal DeCS:

Atributo | Valor
-- | --
Descritor | Dengue
ID do descritor | D003715
Identificador DeCS | 3727

Exemplo de retorno da API para o termo "Dengue":

```
begin: 213,
end: 218,
id: "d003715",
descriptor: "Dengue",
original: "dengue"
```

Exemplo de retorno da API para o termo "Dengue" (valor correto):

```
begin: 213,
end: 218,
id: "3727",
descriptor: "Dengue",
original: "dengue"
```

Para resolver, temos duas opções:

1. Trocar o valor atual do atributo ID pelo valor correto ou
2. Incluir mais um atributo para garantir os dois valores (segue exemplo):

```
begin: 213,
end: 218,
id: "3727",
code: "d003715",
descriptor: "Dengue",
original: "dengue"
```

**Comment by heitorbarbieri** [comment]
@wilsonmoura,  por favor, teste o serviço. 

A saída para o parâmetro dengue (document=dengue) será:

begin: 0
end: 5
decsId: "003727"
id: "d003715"
descriptor: "Dengue"
original: "dengue"

**Comment by wilsonmoura** [comment]
@heitorbarbieri Validado!
