### ISSUE TITLE
Preservar ordem dos termos encontrados na lista de descritores

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/DeCSHighlighter#3]
Conforme verificado o retorno do serviço devolve duas listas (positions e descriptors) na lista positions consta o identificador do descritor e na lista de descriptors consta o nome do descritor, no entanto a lista de descritores se encontra ordenada alfabéticamente não sendo possível relacionar o termo com o seu identificador.

**Comment by heitorbarbieri** [comment]
Optou-se em deixar a lista de descritores em ordem alfabética mas acrescentar o descritor em cada elemento da lista de posições. Veja exemplo abaixo com a sentença "morte por doença":

```{
  "text" : "<em>morte</em> por <em>doença</em>",
  "positions" : [
    {
      "begin" : 0,
      "end" : 4,
      "id" : "003660",
      "descriptor" : "morte"
    },
    {
      "begin" : 10,
      "end" : 15,
      "id" : "028564",
      "descriptor" : "doenca"
    }
  ],
  "descriptors" : [
    "doenca",
    "morte"
  ]
}
```

**Comment by viniciusandrade** [comment]
@heitorbarbieri 
Estou reabrindo este issue pois aparentemente na versão atual foi retirado novamente o elemento "descriptor" da lista de positions não sendo possível relacionar o termo com o seu identificador.

**Comment by heitorbarbieri** [comment]
Refeito no commit b8dcfd3
